services:
  - type: web
    name: englishweb-promax
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cd front_end
      npm install
      npm run build
      cd ..
      python manage.py collectstatic --noinput
    startCommand: gunicorn webtienganh.wsgi:application
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: webtienganh.settings
